# Script arguments
max_frames: 16
data_root: /media/automan/6E94666294662CB1/A_Content/Datasets/ADEChallengeData2016
train_dataset_path: /media/automan/ExSpace/Projects/VideoLISA/dataset/labels/train-10000.json
val_dataset_type: internvid # internvid or activitynet
val_dataset_path: /media/automan/ExSpace/Projects/VideoLISA/dataset/labels/filtered_dataset.json

# Model config
## Backbone part
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
sam_model_path: "/media/automan/ExSpace/Projects/VideoLISA/checkpoints/sam_vit_h_4b8939.pth"
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
## Lora part
target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05

# Trainer config
bf16: true
do_eval: true
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 4
gradient_checkpointing: true      # If false, it will ocupy much memory
#gradient_checkpointing_kwargs:
#  use_reentrant: false
learning_rate: 3.0e-05
log_level: info
logging_steps: 20
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 512
#max_steps: 100
num_train_epochs: 1
output_dir: output/VideoLISA
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- none
save_strategy: "steps"
seed: 42
warmup_ratio: 0.1
save_on_each_node: true
