# Script arguments
data_root:
  coco: /media/automan/6E94666294662CB1/A_Content/Datasets/coco
datasets: refcoco
dataloader_num_workers: 12

# Model config
## Backbone part
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
# Remove this column when image pretraining
sam_model_path: checkpoints/sam2.1_hiera_large.pt
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
## Lora part
target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05

# Trainer config
bf16: true
do_eval: true
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true      # If false, it will ocupy much memory
#gradient_checkpointing_kwargs:
#  use_reentrant: false
learning_rate: 3.0e-05
log_level: info
logging_steps: 20
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 512
#max_steps: 200
num_train_epochs: 1
output_dir: output/pretrain_refseg
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
report_to:
- "wandb"
run_name: pretrain_refseg
save_strategy: "steps"
seed: 42
warmup_ratio: 0.1
save_on_each_node: true
