# Script arguments
max_frames: 12
data_root: /media/automan/6E94666294662CB1/A_Content/Youtube/videos
dataset_path: /media/automan/ExSpace/Projects/VideoLISA/dataset/labels/train-10000.json


# Model config
## Backbone part
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
## Lora part
target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05

# Trainer config
bf16: true
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 1.0e-04
logging_steps: 50
max_steps: 500
num_train_epochs: 5
output_dir: output/Qwen2_5-VL-3B
per_device_train_batch_size: 1
report_to:
- none
save_on_each_node: true

max_seq_length: 512
packing: true